#!/bin/bash
#
# If this script doesn't work look at the output of upower -e and upower -d

bat=`upower -i /org/freedesktop/UPower/devices/battery_BAT0 |
    grep percentage |
    sed 's/ *percentage: *//g'`

state=`upower -i /org/freedesktop/UPower/devices/battery_BAT0 |
    grep state |
    sed 's/ *state: *//'`

if [ $state == "charging" -o $state == "fully-charged" ]; then
    echo -n "^c#9EFF52^ ^c#FFFFFF^"
else
    echo -n "^c#9EFF52^ $(percentage $bat            ) ^c#FFFFFF^"
fi

echo -n "$bat"
